### PR TITLE
Updating Jenkins Version to jenkins/jenkins:lts

### PR DESCRIPTION
**Pull request by Talderon**
This way you don't have to worry about what the current version is. Source:

https://hub.docker.com/_/jenkins/

### CODE REVIEW

**Comment by viglesiasce** [comment]
Thanks @Talderon! Can you sign the CLA and comment back on this issue with `I signed it`.

**Comment by Talderon** [comment]
`I Signed It`

**Comment by Talderon** [comment]
I Signed It

**Comment by Talderon** [comment]
I just got back to reading this error message. I added my gmail email to my account, can this check be kicked off again? Thanks!

**Comment by viglesiasce** [comment]
Hey @Talderon!

Can your remove the changes other than the lts tag update?

To rekick the CLA check, comment here with `I signed it`.

**Comment by Talderon** [comment]
I'm not sure I am understanding what you are talking about. The only change I have is the tag update.

Thanks!

**Comment by snackycracky** [comment]
@Talderon no you have some readme update and some sonar stuff there as well.

**Comment by viglesiasce** [comment]
As of #96 we are using the Helm chart for installation which uses the LTS image:
https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L13

**Pull request closed without merging**
