### PR TITLE
update Jenkins chart

### PR DESCRIPTION
**Pull request by torstenwalter**

### CODE REVIEW

**Comment by torstenwalter** [comment]
I signed it!

**Comment by viglesiasce** [comment]
@davidstanke can you take a look?

**Comment by viglesiasce** [comment]
Oh and thank you for the contribution @torstenwalter!!

**Comment by torstenwalter** [comment]
I rebased it on master. I found this repo while doing a quiklab. So please pay attention that the lab might need an update, too.

BTW: Are you sure you need a PVC with 100GB? For demos a smaller one should be sufficient.

**Comment by davidstanke** [comment]
FYI, I'm updating the lab content; we'll merge this at the same time as that gets published. Thanks again, @torstenwalter !

**Comment by viglesiasce** [comment]
Thanks @torstenwalter for the contrib and @davidstanke for the review and updates.

**Pull request merged**
