### PR TITLE
Update-apiVersion

### PR DESCRIPTION
**Pull request by rohitshah-tudip**
- Updated “apiVersion: apps/v1” replacing “apiVersion: extensions/v1beta1”.
- Reference buganizer: http://b/154966198

### CODE REVIEW

**Comment by jackykumar-tudip** [comment]
@miketruty Please merge this PR.

**Comment by miketruty** [comment]
> @miketruty Please merge this PR.

I do not have permission to merge. @viglesiasce

**Comment by autotune** [comment]
`spec:
  replicas: 1
  selector:
    matchLabels:
      app: master`

Selector needs to be added as above as well @rohitshah-tudip

**Comment by rohitshah-tudip** [comment]
@autotune 
Selector is already added in file backend-production.yaml

metadata:
  name: gceme-backend-production
spec:
  replicas: 1
  selector:
      matchLabels:
          app: gceme
          role: backend
          env: production

Also, I have tested the lab with updated apiVersion and it is working as designed.
Please let me know if there is anything else.

**Pull request merged**
