### PR TITLE
Fix heading levels

### PR DESCRIPTION
**Pull request by Chekote**
The headings used throughout the document are inconsistent. You'll probably never noticed unless you try to generate a table of contents from them, but I cleaned them up anyway.

Before:

* Lab: Build a Continuous Deployment Pipeline with Jenkins and Kubernetes
  * Introduction
  * Prerequisites
  * Do this first
  * Create a Kubernetes Cluster
  * Create namespace and quota for Jenkins
    * Create the Jenkins Home Volume
    * Create a Jenkins Deployment and Service
    * Connect to Jenkins
    * Your progress, and what's next
  * The sample app
  * Deploy the sample app to Kubernetes
    * Create a repository for the sample app source
  * Create a pipeline
    * Phase 1: Add your service account credentials
    * Phase 2: Create a job
    * Phase 3:  Modify Jenkinsfile, then build and test the app
  * Phase 4: Deploy a [canary release](http://martinfowler.com/bliki/CanaryRelease.html) to staging
* Phase 5: Deploy a development branch
    * Deploy the development branch
    * Access the development branch
  * Extra credit: deploy a breaking change, then roll back
  * Clean up

After:

* Lab: Build a Continuous Deployment Pipeline with Jenkins and Kubernetes
  * Introduction
  * Prerequisites
  * Do this first
  * Create a Kubernetes Cluster
  * Create namespace and quota for Jenkins
    * Create the Jenkins Home Volume
    * Create a Jenkins Deployment and Service
    * Connect to Jenkins
    * Your progress, and what's next
  * The sample app
    * Deploy the sample app to Kubernetes
    * Create a repository for the sample app source
  * Create a pipeline
    * Phase 1: Add your service account credentials
    * Phase 2: Create a job
    * Phase 3:  Modify Jenkinsfile, then build and test the app
    * Phase 4: Deploy a [canary release](http://martinfowler.com/bliki/CanaryRelease.html) to staging
    * Phase 5: Deploy a development branch
      * Deploy the development branch
      * Access the development branch
  * Extra credit: deploy a breaking change, then roll back
  * Clean up

### CODE REVIEW

**Comment by viglesiasce** [comment]
Should we have a ToC at the top?

**Comment by Chekote** [comment]
That's a good question. I wish Markdown had a feature to auto-inject one with something like `[ToC]`. Having to manually create one offends my D.R.Y. sensibilities.

**Comment by viglesiasce** [comment]
Fair.

**Comment by viglesiasce** [comment]
I will be offended with you.

**Comment by Chekote** [comment]
I found a [Package for Atom](https://atom.io/packages/markdown-toc) that can generate a table of contents, and automatically update it whenever you save the document. However, this is only going to work in Atom, and it introduces some comment based metadata above and below the table of contents to support the feature.

If we're going to have a ToC, I think we should definitely use the tool to create it. But I'm not too keen on having the tools metadata in the README source. It doesn't feel very clean to introduce a proprietary feature like this into a standards based document like a markdown readme. But the only options I can see at this point are:

  1. Use this tool to generate and maintain the ToC, but leave the metadata in the source.
  2. Use the tool to generate and maintain the ToC, but remove the metadata from the source.
  3. Don't have a ToC.

Please let me know your thoughts.

**Comment by Chekote** [comment]
Looks like it's been a Github wishlist item for a couple of years: https://github.com/isaacs/github/issues/215

**Pull request merged**
