### PR TITLE
Mention Google Oauth plugin as requirement

### PR DESCRIPTION
**Pull request by bodepd**

### CODE REVIEW

**Comment by viglesiasce** [comment]
Thanks @bodepd! Once the CLA is signed I'll merge this in. How did things go aside from this?

**Comment by bodepd** [comment]
It'll take me a few days to figure out all of the contacts for the CLA. While I was able to follow the instructions and get things working, there were a few bits of detail about how things work that weren't entirely clear. Is there a mailing list where I could ask some follow up questions?

**Comment by bodepd** [comment]
@viglesiasce my CLA is now taken care of, but it is listed under my company email address (which is listed on my account, but not the email address that I use for open source contributions.)

**Comment by viglesiasce** [comment]
Thanks @bodepd! I found it. 

As far as follow up questions, if they are related directly to the content in this repo open up an issue to spark up the discussion. 

For container and Kubernetes related inquiries check out:
https://groups.google.com/forum/#!forum/kubernetes-dev
https://groups.google.com/forum/#!forum/google-containers

Thanks again for the contribution!

**Pull request merged**
